### ISSUE TITLE
Change title on homepage

### ISSUE THREAD

**Issue by chtnnh** [chtnnhfoundation/chtnnhfoundation.org#1]
This is a good first issue for those who want to start contributing to the project. 

A good place to start would be to clone the repository and checkout the `pages/index.js` file. 

Reply here if you need any help

**Comment by CheRayLiu** [comment]
Hi @chtnnh could I get assigned to this? thanks

**Comment by chtnnh** [comment]
@CheRayLiu done! could you change the title on the homepage to chtnnh foundation

**Comment by chtnnh** [comment]
Resolved by #14
