### ISSUE TITLE
Change landing page title width to 70% of device width on large screens

### ISSUE THREAD

**Issue by chtnnh** [chtnnhfoundation/chtnnhfoundation.org#2]
This is a good first issue if you want to start contributing to the project. 

A good first step would be to clone the repository and checkout the `pages/index.js` file.

Reply here if you have any questions.

**Comment by adrianghub** [comment]
I'm working on it.

**Comment by adrianghub** [comment]
If you have anything I could work on for this project I'm more than happy to help.
