### ISSUE TITLE
Ensure cards on homepage are the same size

### ISSUE THREAD

**Issue by chtnnh** [chtnnhfoundation/chtnnhfoundation.org#8]
**Describe the bug**
The cards on the homepage differ in size

**To Reproduce**
1. Go to 'https://chtnnhfoundation.org'
2. Scroll down to bottom
3. See error

**Expected behavior**
Cards should be the same size

**Screenshots**
<img width="735" alt="Screen Shot 2022-01-26 at 11 52 22 AM" src="https://user-images.githubusercontent.com/59027776/151123765-904d3f31-3479-40d6-b363-9ec412af2c90.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version Latest

**Additional context**
N/A

**Comment by shoaibahmed997** [comment]
Hello @chtnnh  if this is not assigned to anyone. I'd like to help.

**Comment by chtnnh** [comment]
Hey @shoaibahmed997 for sure!
